### ISSUE TITLE
[FEAT] Approve pull requests with only additions

### ISSUE THREAD

**Issue by abhishekmukherg** [tianhaoz95/approveman#1170]
**Is your feature request related to a problem? Please describe.**
My company is investigating a solution which will allow Pull Requests to get auto-approved if

* The file is in a directory
* AND it is a new file in the directory

The use case for this is an infrastructure gitops repository, where creating a new file (assuming appropriate guardrails enforcing the file is only creating new resources which match the filename) is a generally safe operation. Whereas modifying an _existing_ file should require another human's approval, and should not get auto approved

**Describe the solution you'd like**
Enhance the DSL to have a feature like

```yaml
ownership_rules:
  directory_matching_rules:
      # The name of the rules that is used mainly for logging.
    - name: "Default playground rule for prototyping."
      # The directory that certain user with {{username}} owns.
      path: "playground/{{username}}/**/*"
      # These match the observed output of status from the list files API
      # https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#list-pull-requests-files
      changes:
        - modified
        - removed
        - added
```

The default will be all statuses, but could be modified on a per repository bases like

```yaml
ownership_rules:
  directory_matching_rules:
    - name: "Default playground rule for prototyping."
      path: "playground/{{username}}/**/*"
      changes:
        - added
```

To only approve pull requests which add files

**Describe alternatives you've considered**

* mostly just writing this feature ourselves, whether by forking the code or writing our own version.

**Additional context**

I think we'd be interested to contribute this if the feature is useful for the group
