### ISSUE TITLE
Add optional config to customize approving messages

### ISSUE THREAD

**Issue by tianhaoz95** [tianhaoz95/approveman#78]
It would be a good indicator for the new contributors to see useful information about how ApproveMan is doing right from the pull request comments.

A quick draft design:

```yml
ownership_rules:
  message:
    success: |
      "Thanks {{username}} for opening the request!"
  directory_matching_rules:
    - name: personal projects in experimental
      path: playground/{{username}}/**/*
    - name: personal documentation
      path: docs/personal/{{username}}/**/*
      message:
      success: |
        "Thanks {{username}} for opening the request!"
```

The message can be global or fine grained to be project specific.

We can make it into 2 steps where the first one is global only and the second one is supporting project specific message.
